### ISSUE TITLE
adding taxonomy type in facetted results

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#103]
Some hits returned by the root search query are of type [:Taxonomy](http://purl.bdrc.io/ontology/core/Taxonomy) but currently break the code. I've patched it so that it doesnt break, but these results should be handled properly (see [here](https://github.com/BuddhistDigitalResourceCenter/lds-pdi/blob/fa4a8fc1df923bb09caa5a585e89e154c559459e/src/main/java/io/bdrc/ldspdi/results/library/RootResults.java#L96))

**Comment by eroux** [comment]
(same with etexts that have labels that could be returned)

**Comment by MarcAgate** [comment]
This is addressed in commit 9b3f960 . However, in root search results, only the count of etexts having a chunk containing the requested string is returned (Etexts_count.arq). A second call (in the facet panel) actually serves the etexts details.

**Comment by MarcAgate** [comment]
This should be closed as well. WDYT ?

**Comment by eroux** [comment]
I think so, I actually think it's more an issue in the data: https://github.com/buda-base/git-to-dbs/issues/15 so let's close it here yes
