### ISSUE TITLE
missing colon in individual name

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#115]
http://purl.bdrc.io/ontology/admin/AccessType reads

```
bdrAccessFairUse
```

instead

```
bdr:AccessFairUse
```

**Comment by MarcAgate** [comment]
This is outdated. See http://purl.bdrc.io/admindata/AccessFairUse.ttl or http://library.bdrc.io/show/bda:AccessFairUse. Should be closed.

**Comment by eroux** [comment]
yes
