### ISSUE TITLE
update service not working

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#117]
The updates on owl-schema don't appear in the ontology service, see for instance

http://purl.bdrc.io/ontology/core/langBCP47Lang

while it's defined in [this commit](https://github.com/buda-base/owl-schema/commit/3fce97d4153cfc688aa705b6b81da76e9724a04a)

**Comment by MarcAgate** [comment]
I made sure that models were reloaded for all request sent after the update process. Seems to be working fine now. 
However, the ontology browser doesn't show domain and range info and labels and comments for properties. Fixing that now.

**Comment by MarcAgate** [comment]
props display fixed as of commit 89bee3a
