### ISSUE TITLE
error searching in Etexts

### ISSUE THREAD

**Issue by berger-n** [buda-base/lds-pdi#123]
http://purl.bdrc.io/lib/chunksFacetGraph?LG_NAME=bo-x-ewts&I_LIM=500&L_NAME=%22%27od%20zer%22

returns error 500

**Comment by MarcAgate** [comment]
Precisely, the following templates are timing out: 
_Res_allTypes, Res_oneType, chunksFacetGraph, chunksByEtextGraph, etextFacetGraph_
All of these are using jena: text and all templates not using jena text are responding. Only two templates using jena text are responding: 
_Etexts_contents, Etexts_count_
@xristy 
if the issue eventually comes from jena text, is it possible that we have some outdated indexes or so (on some properties)?

**Comment by eroux** [comment]
I think if jena:text was broken no query would work at all...

**Comment by berger-n** [comment]
http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=bo-x-ewts&I_LIM=500&L_NAME=%22%27od%20zer%22 doesn't work anymore
same error

**Comment by MarcAgate** [comment]
http://purl.bdrc.io/lib/rootSearchGraph?LG_NAME=bo-x-ewts&I_LIM=500&L_NAME=%22%27od%20zer%22 is back up again

**Comment by MarcAgate** [comment]
@eroux 
I just tested jean:text in chunkFacetGraph and it works fine. 
This property path 
_?s ((:workHasItemEtext/:itemHasVolume)/:volumeHasEtext)/:eTextResource ?etext ._ seems to be the one causing the issue:

this simplified query hangs forever:

```
CONSTRUCT
  {
    ?chunk rdf:type :EtextChunk .
    ?chunk :eTextHasChunk ?lit .
    ?chunk :seqNum ?seqNum .
    ?chunk :sliceStartChunk ?startChunk .
    ?chunk :sliceEndChunk ?endChunk .
    ?chunk tmp:forEtext ?etext .
    ?chunk tmp:forWork ?s .
    ?chunk tmp:workLabel ?workLabel .
    ?chunk :creatorMainAuthor ?author .
    ?chunk tmp:authorName ?author_name .
    ?chunk tmp:etextAbout ?about .
    ?chunk tmp:etextGenre ?genre .
    ?chunk :eTextTitle ?etextTitle .
    ?chunk :eTextVolumeIndex ?volIndex .
    ?chunk :eTextIsVolume ?isVolume .
  }
WHERE
  { ( ?chunk ?score ?lit )
            text:query        ( :chunkContents "\"'od zer\""@bo-x-ewts "highlight:" ) .
    ?etext  :eTextHasChunk    ?chunk .
    ?chunk  :seqNum           ?seqNum ;
            :sliceStartChunk  ?startChunk ;
            :sliceEndChunk    ?endChunk .
    ?s ((:workHasItemEtext/:itemHasVolume)/:volumeHasEtext)/:eTextResource ?etext .
    ?etext  :eTextTitle  ?etextTitle
    OPTIONAL
      { ?etext  :eTextIsVolume  ?isVolume }
  }
ORDER BY DESC(?score)
LIMIT   500
``` 
if I comment out the line that uses the property path above, it returns normally.

**Comment by eroux** [comment]
ok... I have to say it's very strange, this should be a straightforward thing... maybe reversing the path would work better? (having `?etext` on the left and `?s` to the right). `?s` could probably also be renamed to `?work`... also, what are the lines

```
    ?chunk tmp:workLabel ?workLabel .
    ?chunk :creatorMainAuthor ?author .
    ?chunk tmp:authorName ?author_name .
    ?chunk tmp:etextAbout ?about .
    ?chunk tmp:etextGenre ?genre .
    ?chunk :eTextVolumeIndex ?volIndex .
```

supposed to do?

**Comment by eroux** [comment]
oh, I see, these lines were in the original sorry

**Comment by MarcAgate** [comment]
What bothers me is that
```
CONSTRUCT
  {   
    ?s tmp:prop ?etext .    
  }
WHERE
  { 
  ?s ((:workHasItemEtext/:itemHasVolume)/:volumeHasEtext)/:eTextResource ?etext .   
  }
LIMIT   500
```
returns just fine...

**Comment by MarcAgate** [comment]
well, chunksFacetGraph works in fuseki endpoint: it just takes forever to return and we therefore got the following in the browser:
```
HttpException: -1 Unexpected error making the query: java.net.SocketTimeoutException: Read timed out
	org.apache.jena.sparql.engine.http.HttpQuery.rewrap(HttpQuery.java:373)
	org.apache.jena.sparql.engine.http.HttpQuery.execPost(HttpQuery.java:358)
```

**Comment by xristy** [comment]
Try putting the ```?I_LIM``` in the ```text:query```:

    (?chunk ?score ?lit) text:query ( :chunkContents ?L_NAME ?I_LIM "highlight:") .

this will cause the Lucene to stop as soon as it finds ?I_LIM results. With the ?I_LIM in the outer sparql Lucene text:query works very hard to find several thousand results before yielding to the outer sparql

**Comment by MarcAgate** [comment]
I tried and that speeds up the process but it is still very slow. The request is still timing out. I think we have to redesign that query or this functionality.

**Comment by xristy** [comment]
The performance was improved by removing the ```none.opt``` file from the ```databases/bdrc/``` dataset. Where do we stand now with this query and the issues that were raised?

**Comment by MarcAgate** [comment]
As far as I can tell, the issue is solved and we can again browse Etexts in the library. 
@berger-n Would you agree with that?

**Comment by berger-n** [comment]
yes I do
