### ISSUE TITLE
counter-intuitive UI for imports

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#125]
The UI for import makes sense but it happens to confuse users, for instance when I go to

http://purl.bdrc.io/ontology/admin/

and I know I want to look for `Access`, the first thing that says access in the ontology

http://purl.bdrc.io/ontology/adm/types/Access

but what I really want is the access class

http://purl.bdrc.io/ontology/admin/Access

I think a way to solve that is to make the imports maybe in a smaller font, and at the end of the page...

**Comment by MarcAgate** [comment]
The UI modification was done as of commit a94550f. However, the adm:Access class is still unaccessible from the admin ontology home page as it is a subclass of adm:Type (which is accessible from the admin ontology home page).

adm:Access (as any other class) is only directly available from its ontology home page: http://purl.bdrc.io/ontology/adm/types/Access/

**Comment by MarcAgate** [comment]
@eroux 
Can we close this one ?
