### ISSUE TITLE
use ont-policy.rdf

### ISSUE THREAD

**Issue by xristy** [buda-base/lds-pdi#127]
The owl-schema/ont-policy.rdf needs to replace ontologies.yml so that updates to the ontology structure is updated on ldspdi w/o any further work. The github webhook should trigger accessing the ontology via 

```java
OntDocumentManager mgrImporting = 
   new OntDocumentManager("https://raw.githubusercontent.com/buda-base/owl-schema/master/ont-policy.rdf");
```
If there is need of some additional information to the defined ont-policy properties, then it is a simple matter to include them. The Jena processing of ont-policy.rdf is lenient w.r.t. the presence of externally defined properties.

**Comment by MarcAgate** [comment]
So far, I have identified that we need a way to mark a given ontology (in our case, admin, bdo and auth) as "viewable" or not, so that would be a boolean. (That's for the dropdown list used on the jsp pages).

**Comment by xristy** [comment]
[d368cd0](https://github.com/buda-base/owl-schema/commit/d368cd08c98937f954024dc4e3925230b8285d13) added `adm:defaultOntGraph`, `adm:ontGraph`, and `adm:ontVisible` as well as `ontology/ext/auth` to `ont-policy.rdf`.
