### ISSUE TITLE
http://purl.bdrc.io/ontology/... fails to return proper contents

### ISSUE THREAD

**Issue by xristy** [buda-base/lds-pdi#129]
For example,

```
curl --header 'Accept application/rdf+xml' http://purl.bdrc.io/ontology/types/Transliteration
```
Is now returning html which is breaking requests. Requesting `text/turtle` also fails.

This is now getting in the way of work on xmltoldmigration.

**Comment by MarcAgate** [comment]
curl -v -H "Accept:application/rdf+xml" http://purl.bdrc.io/ontology/admin/ is working just fine because its publicUri ends with a "/" in ont-policy.rdf.

Make sure that each ontology publicUri ends with a "/" and it should work just fine.

**Comment by xristy** [comment]
What is the semantics of the trailing `/` vs not?

**Comment by MarcAgate** [comment]
well, I don't know: sometimes you put one, sometimes you don't. if you want to leave things as is, I can do more testing including most common cases (trailer '/', trailer ' #', no trailer, etc...) . Just tell me.

**Comment by xristy** [comment]
I thought you might know the answer. I'll try to correct but would like to know. Things were working without `/` but I can adjust in all of the various includes and such.

In any event, ldspdi is responding incorrectly to:

```
curl --header 'Accept application/rdf+xml' http://purl.bdrc.io/ontology/types/Transliteration
```
since it is returning HTML rather than a `406` indication that the desired mime type is not available. See [rfc2616, 14.1 Accept](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1):

> If an Accept header field is present, and if the server cannot send a response which is acceptable according to the combined Accept field value, then the server SHOULD send a 406 (not acceptable) response.

**Comment by xristy** [comment]
apparently fixed by a flurry of commits in ldspdi and owl-schema
