### ISSUE TITLE
nfrs: query name; display; and simple form

### ISSUE THREAD

**Issue by xristy** [buda-base/lds-pdi#13]
In increasing order of effort:

1) add the name of the query along with the number of results and execution time
2) perhaps the name of the query could be a link that when clicked displays the query
3) perhaps a link to display a simple form with text boxes for each of the params

**Comment by MarcAgate** [comment]
I imagine points 1. and 2. apply to the jsp result page, right ?

I am not sure about 3 even though I already thought about it. I might try to implement it if I have time.

**Comment by xristy** [comment]
All 3 ideas are meant to apply to the jsp result page and appropriate links perhaps on the initial landing page.

The third item, simple forms, would greatly enhance the utility of the tool.

**Comment by MarcAgate** [comment]
first version of dynamic forms has been pushed (commit bde4003) - Will be soon fully tested

**Comment by MarcAgate** [comment]
Can we close this one ?

**Comment by xristy** [comment]
I've updated purl.bdrc.io. The form capability is a nice improvement.

The one thing that would be nice is to retain the form field values between "executions"

**Comment by xristy** [comment]
I also notice that when there is an ?LG_name param and that param is not supplied then the query fails owing to some unfortunate substitution. When there is an LG_param it would be best if the ldspdi simply created a literal with no tag. This is useful to allow for queries that run can be used to go through a tag specific analyzer or through a default analyzer.

**Comment by MarcAgate** [comment]
I added way to retain param values but html rendering doesn't display params correctly when they contain double quotes. I don't see for the moment how to handle params like:
 
("mkhan chen" AND ("'od zer" OR "ye shes"))   or "'od zer".

Ex: if I have this in my template:
<input type="text" id="${p}" name="${p}" value="${model.getParamValue(val)}">
then the html will be 
<input type="text" id="L_NAME" name="L_NAME" value=""'od zer""><br>
and nothing appears on the page.

If I remove double quotes in the template, like this:
<input type="text" id="${p}" name="${p}" value=${model.getParamValue(val)}>
then I get:
<input type="text" id="L_NAME" name="L_NAME" value="'od zer"><br>
which renders as 'od zer on the page, but I cannot then submit the correct param which is "'od zer"

Imagine the issue with ("mkhan chen" AND ("'od zer" OR "ye shes")) ...

**Comment by xristy** [comment]
perhaps a solution will present itself. I'll wait to do a new deploy until perhaps tomorrow

**Comment by MarcAgate** [comment]
Hi Chris, can we close this one ? There might be a (complex) solution to it but in our case, I am pretty sure it doesn't worth the effort.
