### ISSUE TITLE
Ontology file: http://purl.bdrc.io/ontology/admin.ttl is not giving as much data as before

### ISSUE THREAD

**Issue by codam** [buda-base/lds-pdi#138]
This morning it was 5000+ lines long, and now it is 700+.
Probably as a result of that, the editor doesn't work anymore.
I tested the editor with the local copy of admin.ttl I did a couple of days ago, and everything works fine with it, so something is definitely wrong with the current admin.ttl file.

**Comment by eroux** [comment]
I think it's because the imports are not merged right? If it's the case let's leave it like that for now...

**Comment by MarcAgate** [comment]
Prior to this morning ldspdi served imported triples along with the requested ontology. Now, imported triples are not served anymore so we can distinguish the specificities of each ontology in our set of ontologies. As a matter of fact when requesting http://purl.bdrc.io/ontology/admin.ttl then ldspdi serves the latest version of https://github.com/buda-base/owl-schema/blob/master/adm/admin.ttl.
The same applies to each ontology (auth, core, types ontologies, etc.)
