### ISSUE TITLE
graph/ and admindata/ not working

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#139]
the `/graph/` and `/admindata/` endpoints don't work correctly:

- http://purl.bdrc.io/admindata/W23819 outputs some turtle with the wrong content-type (html)
- http://purl.bdrc.io/admindata/W23819.ttl doesn't work

it should work just like the `/resource/` endpoint (I can't find any difference actually... graph should just have a different sparql request)

**Comment by eroux** [comment]
I've partially fixed it, the version with extension works, the version without extension still needs fixing

**Comment by MarcAgate** [comment]
I believe this is working properly now. Should we close it ?

**Comment by eroux** [comment]
http://purl.bdrc.io/graph/W23819 still doesn't work properly (wrong mime type)

**Comment by MarcAgate** [comment]
What should that do ? http://purl.bdrc.io/graph/W23819 has `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3`
Should I return content-type='text/turtle' in that case ?

**Comment by eroux** [comment]
It can be either:
- `406`: sorry, no can do html
- `302`: redirect to trig
- `303`: here's a list of formats we can serve the data in
- `200` where the data is encoded in trig and the content type is trig too

anything is better than the incoherent result we currently have. If I have to pick maybe I'd pick 2, but I don't have a strong opinion

**Comment by MarcAgate** [comment]
Ok! so now it's either 300, 406 or 200 with trig serialization and text/trig mime (and obviously 404 when not found).
http://purl.bdrc.io/graph/W23819

**Comment by eroux** [comment]
thanks!

**Comment by MarcAgate** [comment]
I just understood what you meant above so I changed the "default" Response (for accept/html) to a 302 Found with location header set to the requestUri+".trig" (http://purl.bdrc.io/graph/W23819.trig in our case)

**Comment by eroux** [comment]
Ok thanks!
