### ISSUE TITLE
some resources are not imported

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#141]
The triples in [adm/legal_entities.ttl](https://github.com/buda-base/owl-schema/blob/master/adm/legal_entities.ttl) are not imported in the dataset. Running

```sparql
describe bda:LD_BDRC_Open
```

in Fuseki doesn't return any result for instance

**Comment by MarcAgate** [comment]
bda:LD_BDRC_Open is missing in https://github.com/buda-base/owl-schema/blob/master/adm/legal_entities.ttl . it should be added.

**Comment by eroux** [comment]
sorry, thanks!
