### ISSUE TITLE
README.md additions

### ISSUE THREAD

**Issue by xristy** [buda-base/lds-pdi#146]
I think it would be helpful to have a Table of Contents and also a section on endpoints

**Comment by MarcAgate** [comment]
There is now in README.md a table containing all public endpoints description. However, while the table of contents render nicely in MacDown (on my box) they are not showing up on github. As I cannot find any quick way to fix that, I let it as is as far as TOC are concerned.

**Comment by eroux** [comment]
I think the new doc is OK, @xristy can you take a look and close the issue if it works for you?

**Comment by MarcAgate** [comment]
Just added a readable TOC. 
@xristy 
Can we close this one now?
