### ISSUE TITLE
branding should be in the configuration

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#147]
I just got news from DILA that they managed to set up lds-pdi!

http://purl.dila.edu.tw:13280/

Now, as you can see there are some changes to be made to debrand part of the page and put the necessary branding in the configuration.

I think there are two main things to do:
- rename "BDRC Ontology" into "Buddhist Digital Ontology" (that's its name after all, there's a reason for that)
- put all other references to BDRC into configurable strings (can be in the property file)

This should be high priority.

Edit: we should have a little something at the end: this page is run by lds-pdi with a link to this github repo

**Comment by MarcAgate** [comment]
Done as of commit c0be831. However, all ontology homepages have a BDRC logo that needs to be removed (or this could be configurable as well).
I noticed that DILA is using quite an old version of ldspdi (not using the new "splitted" ontology model)

**Comment by eroux** [comment]
well, yes, and I think it makes little sense that their page displays the ontology thing as it should theoretically redirect on ourpage (because the ontology urls start with `purl.bdrc.io`), that's why I wanted the button to switch off the ontology code entirely. I don't remember if it has been implemented... but anyways, the logo should be configurable too yes.

**Comment by MarcAgate** [comment]
The configurable logo is now implemented for the ontology home page http://purl.bdrc.io/ontology/core/

**Comment by eroux** [comment]
thanks!
