### ISSUE TITLE
exposing prefixes

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#148]
related to https://github.com/buda-base/public-digital-library/issues/77 : there should be a way to expose prefixes used on our platform (those of (lds-queries](https://github.com/buda-base/lds-queries/blob/master/public/prefixes.txt)) in a simple manner. I think the most simple would be to have a `/prefixes.ttl` endpoint, serving a ttl file with no triple but all the prefixes definitions. Note that the format of the .txt file in lds-queries is not the same as the ttl format prefix declaration.

**Comment by MarcAgate** [comment]
this was addressed in  commit bd1c21e ( see http://purl.bdrc.io/prefixes)

**Comment by eroux** [comment]
perfect, thanks a lot!
