### ISSUE TITLE
configuration for dataset

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#149]
DILA has their own dataset configured on their Fuseki (not named `bdrcrw`), where is the configuration to point lds-pdi to it? It should be in `/etc/buda/ldspdi` (quite urgent)

**Comment by MarcAgate** [comment]
As the README.md file says:

```
Deployment on a tomcat server :
in tomcat context.xml file, add the following lines:

<Parameter name="fuseki" value="http://<server:port>/fuseki/bdrcrw/query"
         override="false"/>
<Parameter name="queryPath" value="/local/path/to/"
         override="false"/>
```
I don't exactly remember why it is done this way (I just recall it was related to a deployment issue) but I will investigate it. Same thing for the ldspdi.properties file that is used (it is the one in src/main/resources instead of /etc/buda/ldspdi)

**Comment by eroux** [comment]
But that could be overwritten in an update right? I think a file that's not in the repo (and thus cannot be updated) would be best

**Comment by MarcAgate** [comment]
Actually, since we decided to have local props files in dedicated (well known) directories, then the issue related to deployment is gone. Therefore I am going to adapt the code (it's getting the props through the servlet context, [here](https://github.com/buda-base/lds-pdi/blob/master/src/main/java/io/bdrc/ldspdi/service/BootClass.java#L55)) and see how it works.
Same thing for the local lds-queries directory.

**Comment by MarcAgate** [comment]
This has been adressed in commit a3c5a6c.

**Comment by eroux** [comment]
thanks! So... I need to explain them what to do, but I'm not sure it's currently very clear for me... I think we should document the way to configure lds-pdi in the README. Here's a proposal:
- move the API description in a separate file, maybe `API.md` (just copy-pasting)
- add a `ldspdi.properties.template` file in the root of the repo, with a sensible default configuration (although no real password or key of course) and where each line is commented with its meaning. It's not really the case for now, for instance I'm not sure what `PURL` means as a variable

what do you think?

**Comment by MarcAgate** [comment]
OK. For now they can take a look at this config example (used for tests) : 
https://github.com/buda-base/lds-pdi/blob/master/src/test/resources/ldspdiTest.properties

**Comment by eroux** [comment]
well, I saw that but for someone who doesn't know the functioning of ldspdi it's way too obscure... Imagine them thinking "what's the auth graph? i don't have any, what value should I put?". It's a helpful exercice

**Comment by MarcAgate** [comment]
Could we close this one ?

**Comment by eroux** [comment]
yes, thanks
