### ISSUE TITLE
base graph url config

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#150]
There should be an option to configure the base graph url for graphs that are automatically created by ldspdi (the ontology graph for instance), so that Dila can have the automated graph accessible on their own `/graph/` endpoint

**Comment by MarcAgate** [comment]
base graph uris are defined here: https://github.com/buda-base/owl-schema/blob/master/ont-policy.rdf

More specifically: see https://github.com/buda-base/owl-schema/blob/master/ont-policy.rdf#L54 for the default ontologyGraph full URI.

Other base uris are defined in the publicUri property of each OntologySpec object (for instance, see https://github.com/buda-base/owl-schema/blob/master/ont-policy.rdf#L63 )

All this data is loaded at ldspdi startup and each time a push occurs in the owl-schema github repo.

**Comment by eroux** [comment]
ok yes... hmm... let's not mess with that now, it should still be accessible through the a good old query...
