### ISSUE TITLE
https

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#152]
Not super urgent but important in the long term: the https version of purl.bdrc.io should not link to the http one. For instance when I'm on https://purl.bdrc.io/ and I click on "Browse" (an ontology), I'm linked to the https version. On the other hand, we still want the persistent IDs to be http, not https. So we should have links called "persistent ID" on each ontology page, linking to the actual (http) id.

**Comment by MarcAgate** [comment]
Unless I missed something, this has been fully addressed in commit c011b47 . The protocol is now the one chosen by the user. See (ontology pages in particular) from http://purl.bdrc.io and  https://purl.bdrc.io

**Comment by eroux** [comment]
thanks! a final detail, my web browser complains because the logo image is not in https, can you just configure it so that it uses the https version of the image? (it can use the https version all the time).

**Comment by MarcAgate** [comment]
The props file has been updated so the logo is now (and always) served through https !

**Comment by eroux** [comment]
perfect, thanks!

**Comment by MarcAgate** [comment]
All issues have been fixed !
