### ISSUE TITLE
configuration for prefixes / full URIs

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#153]
I just realize there's an even more fundamental thing to do before DILA can use ldspdi: 

```
/resource/{res}
```

is hardcoded to serve `bdr:{res}` / `http://purl.bdrc.io/resource/{res}` (see [this line](https://github.com/buda-base/lds-pdi/blob/master/src/main/java/io/bdrc/ldspdi/rest/resources/PublicDataResource.java#L292)). The same is true for `/admindata/` and `/graph/`. There should be configuration for that in the `ldspdi.properties` file. For instance:

```
endpoints.resource.shortprefix = bdr:
endpoints.resource.fullprefix = http://purl.bdrc.io/resource/
endpoints.admindata.shortprefix = bda:
endpoints.admindata.fullprefix = http://purl.bdrc.io/admindata/
endpoints.graph.shortprefix = bdg:
endpoints.graph.fullprefix = http://purl.bdrc.io/graph/
```

This is quite high priority

**Comment by MarcAgate** [comment]
This has been fixed in commit c8692e4
