### ISSUE TITLE
completing API documentation

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#155]
I've reworked the API documentation a bit, and there are a few things I didn't really know how to fill in this table: https://github.com/buda-base/lds-pdi/blob/master/API.md#controling-the-output @MarcAgate can you replace the `?` with the appropriate values?

**Comment by MarcAgate** [comment]
Done as of commit 03ea3fe. I actually removed the profile parameter and added a **csv_f** format value for full csv.

**Comment by eroux** [comment]
ok thanks! I think there's some code that's counting on the old api, we'll see if someone complains...
