### ISSUE TITLE
configuring taxonomy root

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#156]
It's not really necessary right now, but in the future DILA will probably want their own taxonomy. So we should probably have a config instead of the hardcoded value at https://github.com/buda-base/lds-pdi/blob/master/src/main/java/io/bdrc/taxonomy/Taxonomy.java#L37

**Comment by eroux** [comment]
as well as https://github.com/buda-base/lds-pdi/blob/master/src/main/java/io/bdrc/taxonomy/TaxModel.java#L21

**Comment by MarcAgate** [comment]
Fixed as of commit 4de6ae
