### ISSUE TITLE
limit in text queries

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#159]
For each parameter of text queries that has `isLucene=true`, we currently have an extra argument which is the lang tag, for instance `L_NAME` -> `LG_NAME`. We should also have a `LI_NAME` which would be an integer holding the value of the limit of the text query passed to fuseki. The default (when not provided by the user) should be perhaps `1000`. 

So taking the example, if we have the template:

```sparql
( ?s ?sc ?litC ) text:query ( skos:prefLabel ?L_NAME "highlight:" ) .
```

when passing the arguments `L_NAME="foo"&LG_NAME=en&LI_NAME=400`, the text query should look like:

```sparql
( ?s ?sc ?litC ) text:query ( skos:prefLabel "foo"@en 400 "highlight:" ) .
```

**Comment by MarcAgate** [comment]
fixed as of commit 24c58bb

**Comment by eroux** [comment]
thanks!

**Comment by eroux** [comment]
I think we need to have a default value for `text_query_limit` somewhere though, and have it in the properties template, reopening to track it

**Comment by MarcAgate** [comment]
There is one in the props file. I just forgot to update the props template.
Basically, either we have a LI_XXX in the query or the value set in properties file is used. Do you think of a different logic ?

**Comment by eroux** [comment]
no, looks good, thanks!
