### ISSUE TITLE
quad serialization for graphs

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#160]
The current result of 

http://purl.bdrc.io/graph/W19740.trig

only has triples, no graph indication. All the triples should be in the graph `http://purl.bdrc.io/graph/W19740`

**Comment by MarcAgate** [comment]
Done as of commit e8c54e2

See http://purl.bdrc.io/graph/W19740 ,  http://purl.bdrc.io/graph/W19740.trig and http://purl.bdrc.io/resource/W19740.trig

**Comment by MarcAgate** [comment]
@eroux 
Can we close this one now ?
