### ISSUE TITLE
strange 500 error instead of 404

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#161]
this:

http://purl.bdrc.io/query/graph/ResInfo?I_LIM=500&R_RES=bda:WMNBCA

should give a 404 at worse, not a 500, also the exception mapping is weird now, we are presented with this quite unhelpful html page instead of a a json with some info

**Comment by eroux** [comment]
another on http://purl.bdrc.io/query/table/Work_ImgList?R_RES=bdr:W1FPl2251&format=csv&profile=simple&pageSize=500

**Comment by MarcAgate** [comment]
Done as of commit 713c823
 In the second case you mentioned, the issue was an empty result set (http://purl.bdrc.io/query/table/Work_ImgList?R_RES=bdr:W1FPl2251&pageSize=500) not handled properly for the csv format.

**Comment by MarcAgate** [comment]
@eroux 
Can we close this one now ?
