### ISSUE TITLE
shutting up debug messages

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#162]
ldspdi logs crazy debug messages all the time, I can't find a way to stop them. @MarcAgate can you please look at this? This is high priority

**Comment by MarcAgate** [comment]
This has been addressed now using a basic Logback.xml file in /etc/buda/ldspdi. Therefore, I think we can close this issue.

**Comment by MarcAgate** [comment]
@eroux 
Can we close this one now ?
