### ISSUE TITLE
ldspdi can't start

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#163]
I'm getting this exception when ldspdi starts (in Vagrant):

```
java.lang.NoSuchMethodError: javax.servlet.ServletContext.getVirtualServerName
```

@MarcAgate ldspdi *needs* to be fully working again, I'm really upset that the core functionality of our system is in a non-working state, this is your top priority, please fix it ASAP

**Comment by MarcAgate** [comment]
I think we can close this one. The whole vagrant process has been reviewed and is up to date.

**Comment by MarcAgate** [comment]
@eroux 
Can we close this one ?

**Comment by eroux** [comment]
yes thanks!
