### ISSUE TITLE
allow workAllAssociations to return a person

### ISSUE THREAD

**Issue by berger-n** [buda-base/lds-pdi#165]
`workAllAssociations` should return work creator
[query](https://github.com/buda-base/lds-queries/commit/6057bedb22ab6033a453ae46d23523fed3562eee#diff-a4dbe221709f5d8fff14f36eda71b6d0) is ready but seems to return error 500 because type `Person` not allowed in results

**Comment by MarcAgate** [comment]
Fixed as of commit 0c147a4

See for example http://purl.bdrc.io/lib/workAllAssociations?I_LIM=500&R_RES=bdr%3AW0GR0302&format=json
