### ISSUE TITLE
XML serialization of sparql results

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#168]
For some partners (like 84000), it would be useful to have an xml serialization of the sparql results (for `select` queries). There is a spec for these: https://www.w3.org/TR/rdf-sparql-XMLres/

**Comment by MarcAgate** [comment]
Done as of commit c81283b28897e43539f0a4c5212787fac6beaf76

see for example http://purl.bdrc.io/query/table/Work_outline?R_id=bdr:W12827&format=xml

**Comment by eroux** [comment]
thanks!
