### ISSUE TITLE
pagesize parameter doesn't work in table queries

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#169]
http://purl.bdrc.io/query/table/Cat_idx_info?R_RES=bdr:W22084&R_IdxProp=bdo:workKaTenSiglaD&format=csv&pageSize=5000 returns 50 results instead of the expected ~1200... @MarcAgate can you look at that in high priority?

**Comment by MarcAgate** [comment]
related to #170 
For now, ldspdi sends back an error message (using http 403 status) indicating that the requested pageSize exceeds the limit set in the configuration (default=500).

**Comment by eroux** [comment]
ok thanks
