### ISSUE TITLE
include DateIndications when retrieving resources

### ISSUE THREAD

**Issue by xristy** [buda-base/lds-pdi#171]
We have added `:DateIndication`s to represent the date form for date info in an `:Event`. When retrieving a resource via `http://purlbdrcio/resource/`, for example in [W1FEMC010026](http://purl.bdrc.io/resource/W1FEMC010026.ttl):
```
bdr:EVA8FDDA4BA9FC  a  bdo:CompletedEvent ;
   bdo:dateIndication  bdr:DTDE285DE34F3E ;
   bdo:notAfter  "1958"^^xsd:gYear ;
   bdo:notBefore  "1957"^^xsd:gYear .
```
the resource `bdr:DTDE285DE34F3E` should be included:
```
bdr:DTDE285DE34F3E  a  bdo:DateIndication ;
   bdo:era       bdr:EraBE ;
   bdo:yearInEra  2500 .
```
in the result.

**Comment by MarcAgate** [comment]
Done as of https://github.com/buda-base/lds-queries/commit/7aea8d55ed737e13831945bba2263d69e38580bc (in lds-queries repo).
See http://purl.bdrc.io/resource/W1FEMC010026.ttl

**Comment by MarcAgate** [comment]
@xristy 
Can we close this ?
