### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by berger-n** [buda-base/lds-pdi#176]
* http://library-dev.bdrc.io/show/bdr:W22003 has a translation `eftr:WAETOH360` which there is no data about in fuseki (same thing in http://library-dev.bdrc.io/show/eftr:WAITOH16?cw=none)
* http://library-dev.bdrc.io/show/bdr:P4954 used to have some sameAs information, either from dila ? wikidata ? I don't remember but I bookmarked it to check how it renders

**Comment by MarcAgate** [comment]
I believe this has changed (as W22003 doesn't show a eftr:WAETOH360 transalation anymore. (http://purl.bdrc.io/resource/W22003.ttl). @berger-n :can we close the issue ?
