### ISSUE TITLE
Columbia IDs

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#179]
Due to the renaming of the records, there's something that we need to do for some external links to continue working. I've uploaded the list of records that need to be handled in this was in `src/main/resources/columbia-ids.csv`, here's what needs to be done:

For each `{RID}` in the csv list,

when `purl.bdrc.io/resource/{RID}` is called with the "html" http accept header

compute a new modified RID starting with `W` instead of `I` (ex: `I00JR625` --> `W00JR625`

redirect to html as if the initial identifier was the new record, for instance redirect to `library.bdrc.io/show/bdr:W00JR625`.

There's no change in any other case (ex: RID not in the list, accept header not html, etc.).

**Comment by MarcAgate** [comment]
Done as of commit b047493

**Comment by eroux** [comment]
thanks! can you merge master into newbiblio?

**Comment by eroux** [comment]
this doesn't work anymore... @MarcAgate could you take a quick look? See for instance http://purl.bdrc.io/resource/I23714
