### ISSUE TITLE
export to RIS

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#216]
tbrc.org has a [RIS](https://en.wikipedia.org/wiki/RIS_(file_format)) export, for instance

curl -v 'https://www.tbrc.org/cite?type=ris&rid=W3CN1317'

```
< HTTP/1.1 200 OK
< Content-Type: application/x-research-info-systems;charset=ISO-8859-1
< Date: Tue, 08 Jun 2021 11:54:42 GMT
< Server: Apache-Coyote/1.1
< Content-Length: 208
< Connection: keep-alive
< 
TY  - ELEC
ID  - W3CN1317
TI  - bi en na slob chen du 'khyar ba'i bka' 'gyur bris ma thor bu pod dgu/
UR  - http://tbrc.org/link?RID=W3CN1317
KW  - bka' 'gyur/ 
PB  - [s.n.]
Y1  - [n.d.]
CY  - [ Bathang ]
ER
```

it would be good to also have that on BUDA

**Comment by eroux** [comment]
@xristy I'm making good progress on that, but I'm wondering if you could point me to the code that generates the RIS on https://www.tbrc.org/cite?type=ris&rid=W3CN1317 ?

**Comment by xristy** [comment]
@eroux see org.tbrc.gwt.common/src/org/tbrc/gwt/common/server/Citation.java Line# 524:
```
protected void sendRisCitation(XmlDocs docs, HttpServletResponse response, String ipAddr)
```

**Comment by eroux** [comment]
ah thanks! we do have the source code in a zip file on s3 right? I can't find it at first glance, do you remember where it is?

**Comment by xristy** [comment]
with all the moving of stuff I have no idea. I'll zip up my eclipse workspace and upload somewhere

**Comment by xristy** [comment]
I'm uploading zips of the various projects from my eclipse 4.5 workspace to s3://indium-e4.5-workspace. The svn repo dumps from cloudforge are in s3://svn.projects.tbrc.org but hopefully what I'm uploading will be easier to use in the future for code reference.

**Comment by eroux** [comment]
ah excellent, thanks a lot
