### ISSUE TITLE
etext download out of order in some specific cases

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#226]
https://library.bdrc.io/show/bdr:UT22946_001_0001?backToEtext=bdr:IE22946#open-viewer is correct in the viewer but out of order in the download. This seems a come back of what was fixed in https://github.com/buda-base/lds-pdi/commit/28164747cf8720696923333df0e85606aaaecb75

**Comment by shenzo1** [comment]
Same issue here on the gdam ngag mdzod:
https://library.bdrc.io/show/bdr:UT23605_001_0003?backToEtext=bdr:IE23605#open-viewer
Common attribute is that both are computer inputed texts.

**Comment by shenzo1** [comment]
Same issue here on the rin chen gter mdzod:
https://library.bdrc.io/show/bdr:UT1KG14_001_0002?backToEtext=bdr:IE1KG14#open-viewer
Computer imputed.

**Comment by shenzo1** [comment]
Same issue here:
https://library.bdrc.io/show/bdr:IE1KG6257

OCR

**Comment by shenzo1** [comment]
Hi Elie,

I am encountering the same scrambling issues on the bstan 'gyur here: https://library.bdrc.io/show/bdr:IE23703

Do you have an idea of what is causing all these texts not being in order in their download version?

**Comment by eroux** [comment]
@shenzo1 sorry it took me so long to look at this! this should be fixed now, can you take a look?

**Comment by shenzo1** [comment]
Woohoo!!! Merci Élie !!! C'est impeccable maintenant !!

**Comment by eroux** [comment]
thanks!
