### ISSUE TITLE
955 MARC record

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#230]
Google Books are asking that we put a 955 field, but I'm not sure how it's supposed to be encoded... the MARC export of tbrc.org did have it ([example](https://legacy.tbrc.org/public?module=work&query=marc&args=W22084)), but I think Columbia asked us to remove it. Harvard will also be probably unhappy if we add it... it seems not to be specified anywhere and the example they give only has one `955__$b`. I propose we add a field for now and that we remove it once the export to Google Books is done (so that then we can export to Harvard and IA again). I propose it looks like

```xml
                 <datafield tag="955" ind1=" " ind2=" ">
			<subfield code="b">bdr:W22084</subfield>
		</datafield>
```

@TBRC-TimB can you check with Ben if that works for him?

**Comment by eroux** [comment]
sorry, never mind, they have a more complete example on https://docs.google.com/document/d/1jLF95uxfFVcCRqLXY6USWH0scvjtJkkcC2R4flleyj4/edit which looks more like the output of tbrc.org, except it will use `$b` and `$v` instead of `$a` and `$c`. Another difference with tbrc.org is that we will have `I0846` instead of `0846` for the image group. I also propose we do something like:

```xml
<datafield tag="955" ind1=" " ind2=" ">
   <subfield code="b">I0979</subfield>
   <subfield code="c">v. 1</subfield>
</datafield>
```

but on the other hand https://docs.google.com/document/d/1It001ONn9CbNgIorYA9kVBhpGfeUevHpN0Gb9YRIWvM/edit seems to indicate that we need a library barcode of some sort... ah, MARC is full of so many mysteries, it's really wonderful

**Comment by TBRC-TimB** [comment]
That works for me. I can send the second example along to Ben. 
I do want to point out that we are planning on doing a long term uploading to google books so adding the field temporarily might not be a permanent solution. I'm not sure we want a specific output for each of our distribution partners, so we may have to find a clever solution. 

And all that certainly falls under the mysteries of marc.

**Comment by TBRC-TimB** [comment]
Just to reiterate here, this is the response I got from Ben : 

Our parser expects the 955 subfields to be consistent with those in the records you posted back in [June](https://drive.google.com/corp/drive/folders/1OFBsgsBx8hatmFdtdqEb3ENXnYkhTOF6).  Here's an excerpt from one of them:

 <datafield tag="955" ind1=" " ind2=" ">
        <subfield code="a">W1AC343-I4PD4376</subfield>
        <subfield code="c">v.7</subfield>
    </datafield>

So the barcode was in subfield a, but the enumeration/chronology were indeed in subfield b. So maybe just changing the b in your example to an a would do the job, assuming the I0979 in your example is a barcode (though if it is, it doesn't fit our expectation of what your barcodes look like as described in the attached questionnaire).

If you can just match what we got in June, we'll be okay.

**Comment by jimk-bdrc** [comment]
@TBRC-Timb FWIW that's consistent with the [Bibliographic Metadata document,](https://docs.google.com/document/d/1jLF95uxfFVcCRqLXY6USWH0scvjtJkkcC2R4flleyj4/edit) (cited above) which specifices PSUEDO Barcodes (p.14) it says they can't be used in digitization, but we've already digitized, so I don't know if that's a deal breaker.

**Comment by jimk-bdrc** [comment]
> to be encoded... the MARC export of tbrc.org did have it ([example](https://legacy.tbrc.org/public?module=work&query=marc&args=W22084)), but I think Columbia asked us to remove it. Harvard will also be probably unhappy if we add it... it seems not to be specified anywhere and the example they give only has one `955__$b`.


MARC 9xx says that this field might not always be OCLC compliant, so maybe Columbia would never like it. Is there any prayer of subclassing the MARC generator to provide add this node, and having it be constructed by an extra parameter in the request (&type=GOOGLE_BOOKS) or something?

**Comment by eroux** [comment]
I think I'll implement a URL query parameter yes (`?format=google_books`), that's a good idea! I should be able to do that tomorrow, if not early next week

**Comment by eroux** [comment]
@TBRC-TimB I've add the `955` field behind a `?style=google_books` URL parameter, example: https://purl.bdrc.io/resource/W22084.mrcx?style=google_books . Tell me if it's satisfactory

**Comment by eroux** [comment]
@TBRC-TimB I think we can close this one right?

**Comment by TBRC-TimB** [comment]
Yes I think this is all good. I'll close it.

**Comment by eroux** [comment]
thanks!
