### ISSUE TITLE
integrating ContextGenerator

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#39]
Now that we have the context url in place, we could remove the `context.jsonld` from the owl-file repo and just serve it on lds-pdi. It is automatically generated from the ontology through the [ContextGenerator](https://github.com/BuddhistDigitalResourceCenter/xmltoldmigration/blob/master/src/main/java/io/bdrc/xmltoldmigration/helpers/ContextGenerator.java) class that could be moved from xmltold to here. This is more a reminder than an urgent thing to do.

**Comment by MarcAgate** [comment]
I think this is really outdated. We serve context.jsonld (http://purl.bdrc.io/context.jsonld) but it's not compliant with our current model.

**Comment by eroux** [comment]
right yes, we should update the context.json but that's another issue
