### ISSUE TITLE
using RDFConnectionFuseki

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-pdi#47]
I think it would be worth contemplating the use of `RDFConnectionFuseki` (implementing `SparqlQueryConnection`) for SPARQL queries (instead of using `QueryExecutionFactory`), I think there might be a little gain although probably not measurable by running isolated queries. I'm not sure how it plays with multi-thread so maybe there will need to be one instance per user request, but one of the advantages would be the use of RDF Thrift. It's really no urgent thing, just a note for when things calm down...

**Comment by MarcAgate** [comment]
Done as of commit 4303985. 
Note that this is applicable for construct and describe query types.
SelectQuery type requires the use of a java.util.function.Consumer object that is not practical regarding the way we consume ResultSets in our implementation.

**Comment by eroux** [comment]
Ok, thanks a lot!
