### ISSUE TITLE
handling intersection domain in Ontology service

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/lds-pdi#91]
We have this in bdrc.owl
```
<owl:ObjectProperty rdf:about="http://purl.bdrc.io/ontology/core/hasIncarnation">
        <owl:inverseOf rdf:resource="http://purl.bdrc.io/ontology/core/isIncarnation"/>
        <rdfs:domain>
            <owl:Class>
               
--------------------------------------------------------------------
>                 <owl:unionOf rdf:parseType="Collection">
>                     <rdf:Description rdf:about="http://purl.bdrc.io/ontology/core/Person"/>
>                     <rdf:Description rdf:about="http://purl.bdrc.io/ontology/core/Topic"/>
>                 </owl:unionOf>
--------------------------------------------------------------------
            </owl:Class>
        </rdfs:domain>
        <rdfs:range rdf:resource="http://purl.bdrc.io/ontology/core/Person"/>
        <inferSubTree rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</inferSubTree>
        <rdfs:comment xml:lang="en">This property is applicable to Persons and Topics (that represent deities or other ahistorical figures).</rdfs:comment>
        <rdfs:label xml:lang="en">has incarnation</rdfs:label>
    </owl:ObjectProperty>
```
and when it lists the statements of the owl model, jena returns for the domain:

`[http://purl.bdrc.io/ontology/core/hasIncarnation, http://www.w3.org/2000/01/rdf-schema#domain, 2f798e96-759e-48e0-98dc-e1962d61f63b]`

which is (or looks like) a blank node...

There should be a way to get both "http://purl.bdrc.io/ontology/core/Person" and "http://purl.bdrc.io/ontology/core/Topic" when listing all the statements of the "http://purl.bdrc.io/ontology/core/hasIncarnation" resource

**Comment by MarcAgate** [comment]
Where should this appear ? I might have already adress this issue since both http://purl.bdrc.io/ontology/core/hasIncarnation.ttl and http://purl.bdrc.io/ontology/core/hasIncarnation show the complete domain. The same applies for Range.

**Comment by eroux** [comment]
I think the current state is good enough, maybe it would be clearer with " :Person **or**  :Topic" but that's quite minor

**Comment by MarcAgate** [comment]
This has been fixed a while ago. See here (the domain) for example: http://purl.bdrc.io/ontology/core/hasIncarnation
